// Generated by CoffeeScript 1.4.0
(function() {

  window.ourApp.factory('Categories', [
    '$resource', function($resource) {
      return $resource('http://swally.herokuapp.com/category');
    }
  ]);

  window.ourApp.factory('Pleges', [
    '$resource', function($resource) {
      return $resource('http://swally.herokuapp.com/pledges');
    }
  ]);

}).call(this);
