// Generated by CoffeeScript 1.4.0
(function() {

  describe('Test Pledge controller', function() {
    beforeEach('ourApp');
    ctrl;

    scope;

    return beforeEach(inject(function($controller, $rootScope) {
      var ctrl, scope;
      scope = $rootScope.$new();
      return ctrl = $controller('PledgesCtrl', {
        $scope: scope
      });
    }));
  });

}).call(this);
